# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export TERM="xterm-256color"

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="spaceship"

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
    # essentials
    common-aliases
    command-not-found

    # look & feel
    zsh-syntax-highlighting
    zsh-autosuggestions

    # tools
    git
    git-extras

    python
    pyenv

    docker
    jsontools  # pp_json, is_json, urlencode_json, urldecode_json

    sudo  # ESC twice: Puts sudo in front of the current command, or the last one if the command line is empty.
)

# User configuration
export PATH="$HOME/bin:$PATH"

# zsh-autosuggest configuration
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=243"

# spaceship theme configuration
SPACESHIP_PROMPT_ADD_NEWLINE=false
SPACESHIP_PROMPT_SEPARATE_LINE=false

SPACESHIP_TIME_SHOW=true
SPACESHIP_TIME_COLOR=167

SPACESHIP_DIR_TRUNC=0
SPACESHIP_DIR_TRUNC_REPO=false
SPACESHIP_DIR_COLOR=035

SPACESHIP_EXIT_CODE_SHOW=true

SPACESHIP_PROMPT_ORDER=(
  time          # Time stampts section
  dir           # Current directory section
  git           # Git section (git_branch + git_status)
  rust          # Rust section
  docker        # Docker section
  venv          # virtualenv section
  pyenv         # Pyenv section
  exec_time     # Execution time
  battery       # Battery level and status
  vi_mode       # Vi-mode indicator
  jobs          # Background jobs indicator
  exit_code     # Exit code section
  char          # Prompt character
)

source $ZSH/oh-my-zsh.sh
source ~/.zsh_aliases

# change autosuggest accept key binding to Ctrl + Space
bindkey '^ ' autosuggest-accept

# do not share history between different terminals/consoles
unsetopt share_history

# set compact prompt
function _COMPACT_PROMPT() {
    PROMPT="[%?] %d $ "
}

export EDITOR='vim'

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
alias zshconfig="vim ~/.zshrc"
alias ohmyzsh="vim ~/.oh-my-zsh"
